<?php

/**
 * @file
 * Functions to support theming in the Alliance theme.
 */

use Drupal\file\Entity\File;

/**
 * Implements hook_preprocess_HOOK() for html.html.twig.
 */
function alliance_preprocess_html(&$variables) {

}

/**
 * Implements hook_preprocess_HOOK() for page.html.twig.
 */
function alliance_preprocess_page(&$variables) {
  $variables['theme'] = alliance_get_settings();
}

/**
 * Implements hook_preprocess_HOOK() for node.html.twig.
 */
function alliance_preprocess_node(&$variables) {
  $variables['theme'] = alliance_get_settings();
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function alliance_theme_suggestions_node_alter(array &$suggestions, array $variables) {
  if(isset($variables['elements']['#node']) && $variables['elements']['#node']->id() == 10)
    $suggestions[]='node__contacts';
}
function alliance_get_settings(){
  $theme['phone']['#markup'] = theme_get_setting('phone');
  $theme['address']['#markup'] = theme_get_setting('address');
  $theme['work']['#markup'] = theme_get_setting('work');
  $theme['telegram']['#markup'] = theme_get_setting('telegram');
  $theme['whatsapp']['#markup'] = theme_get_setting('whatsapp');
  $theme['uraddress']['#markup'] = theme_get_setting('uraddress');
  $theme['mail']['#markup'] = theme_get_setting('mail');
  $theme['inn']['#markup'] = theme_get_setting('inn');
  $theme['vk']['#markup'] = theme_get_setting('vk');
  $theme['ogrn']['#markup'] = theme_get_setting('ogrn');
  $theme['nameorg']['#markup'] = theme_get_setting('nameorg');
  $fid = theme_get_setting('file');
  $file = File::load(reset($fid));
  $theme['file'] = \Drupal::service('file_url_generator')->generateAbsoluteString($file->uri->value);
  return $theme;
}
